/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LoginController;
import Controller.RegProgramController;
import Model.Eggrafi;
import Model.Synedria;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Errikos
 */
public class UIProgramRegister extends javax.swing.JFrame {

    /**
     * Creates new form UIProgramRegister
     */
    private RegProgramController cReg;
    private LoginController cLogin;
    /** Creates new form UILogin */
    public UIProgramRegister(RegProgramController cReg) {
        this.cReg = cReg;
        //this.cLogin=cLogin;
        initComponents();
        //System.out.print(cReg.synedriaList.get(1).getGymnasti() );
       //regbtn16.setText();
       Calendar calendar = Calendar.getInstance();
        int day = calendar.get(Calendar.DAY_OF_WEEK); 

        switch (day) {
        case Calendar.MONDAY:
           regDe.setForeground(Color.red);     
             break;
        case Calendar.TUESDAY:
          regTr.setForeground(Color.red);
        // etc.
        break;
        
        case Calendar.WEDNESDAY:
           regTe.setForeground(Color.red);
        break;
        
        case Calendar.THURSDAY:
           regPe.setForeground(Color.red);
        break;
        
        case Calendar.FRIDAY:
           regPa.setForeground(Color.red);
        break;
}
    }
   
    static int idbtn=0;

    UIProgramRegister() {
        initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userdia1 = new javax.swing.JDialog();
        daylb = new javax.swing.JLabel();
        cancel2 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        gymnastislb = new javax.swing.JLabel();
        aithousalb = new javax.swing.JLabel();
        programmalb = new javax.swing.JLabel();
        timelb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        theseis = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        regPa = new javax.swing.JLabel();
        regPe = new javax.swing.JLabel();
        regTe = new javax.swing.JLabel();
        regTr = new javax.swing.JLabel();
        regDe = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        regbtn12 = new javax.swing.JButton();
        regbtn16 = new javax.swing.JButton();
        regbtn2 = new javax.swing.JButton();
        regbtn3 = new javax.swing.JButton();
        regbtn20 = new javax.swing.JButton();
        regbtn7 = new javax.swing.JButton();
        regbtn11 = new javax.swing.JButton();
        regbtn15 = new javax.swing.JButton();
        regbtn19 = new javax.swing.JButton();
        regbtn4 = new javax.swing.JButton();
        regbtn1 = new javax.swing.JButton();
        regbtn5 = new javax.swing.JButton();
        regbtn9 = new javax.swing.JButton();
        regbtn13 = new javax.swing.JButton();
        regbtn17 = new javax.swing.JButton();
        regbtn6 = new javax.swing.JButton();
        regbtn10 = new javax.swing.JButton();
        regbtn14 = new javax.swing.JButton();
        regbtn18 = new javax.swing.JButton();
        regbtn8 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        load = new javax.swing.JToggleButton();

        userdia1.setTitle("Πληροφοριες Προγραμματος");

        daylb.setText("-");

        cancel2.setText("close");
        cancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel2ActionPerformed(evt);
            }
        });

        jLabel47.setText("Γυμναστης:");

        jLabel48.setText("Αιθουσα:");

        jLabel49.setText("Προγραμμα");

        jLabel50.setText("Ημερα:");

        jLabel51.setText("ωρα: ");

        gymnastislb.setText("-");

        aithousalb.setText("-");

        programmalb.setText("-");

        timelb.setText("-");

        jLabel1.setText("Θεσεις: ");

        theseis.setText("-");

        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userdia1Layout = new javax.swing.GroupLayout(userdia1.getContentPane());
        userdia1.getContentPane().setLayout(userdia1Layout);
        userdia1Layout.setHorizontalGroup(
            userdia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userdia1Layout.createSequentialGroup()
                .addGroup(userdia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userdia1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(userdia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userdia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(18, 18, 18)
                        .addGroup(userdia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(programmalb, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(aithousalb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gymnastislb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(userdia1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(daylb)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timelb))
                    .addGroup(userdia1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(register)
                        .addGap(20, 20, 20)
                        .addComponent(cancel2))
                    .addGroup(userdia1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(theseis, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        userdia1Layout.setVerticalGroup(
            userdia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userdia1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(userdia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daylb)
                    .addComponent(jLabel50)
                    .addComponent(jLabel51)
                    .addComponent(timelb))
                .addGap(54, 54, 54)
                .addGroup(userdia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(gymnastislb))
                .addGap(27, 27, 27)
                .addGroup(userdia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(aithousalb))
                .addGap(18, 18, 18)
                .addGroup(userdia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(programmalb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userdia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(theseis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(userdia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel2)
                    .addComponent(register))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Δηλωση Σε προγραμμα");

        regPa.setText("Παρασκευη");

        regPe.setText("Πεμπτη");

        regTe.setText("Τεταρτη");

        regTr.setText("Τριτη");

        regDe.setText("Δευτερα");

        userName.setText("UserName");

        jLabel60.setText("9-11");

        jLabel36.setText("11-1");

        jLabel54.setText("4-6");

        jLabel55.setText("6-8");

        regbtn12.setText("EMPTY");
        regbtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtn12ActionPerformed(evt);
            }
        });

        regbtn16.setText("EMPTY");
        regbtn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtn16ActionPerformed(evt);
            }
        });

        regbtn2.setText("EMPTY");
        regbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtn2ActionPerformed(evt);
            }
        });

        regbtn3.setText("EMPTY");
        regbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtn3ActionPerformed(evt);
            }
        });

        regbtn20.setText("EMPTY");
        regbtn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtn20ActionPerformed(evt);
            }
        });

        regbtn7.setText("EMPTY");
        regbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtn7ActionPerformed(evt);
            }
        });

        regbtn11.setText("EMPTY");
        regbtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtn11ActionPerformed(evt);
            }
        });

        regbtn15.setText("EMPTY");
        regbtn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtn15ActionPerformed(evt);
            }
        });

        regbtn19.setText("EMPTY");
        regbtn19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtn19ActionPerformed(evt);
            }
        });

        regbtn4.setText("EMPTY");
        regbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtn4ActionPerformed(evt);
            }
        });

        regbtn1.setText("EMPTY");
        regbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtn1ActionPerformed(evt);
            }
        });

        regbtn5.setText("EMPTY");
        regbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtn5ActionPerformed(evt);
            }
        });

        regbtn9.setText("EMPTY");
        regbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtn9ActionPerformed(evt);
            }
        });

        regbtn13.setText("EMPTY");
        regbtn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtn13ActionPerformed(evt);
            }
        });

        regbtn17.setText("EMPTY");
        regbtn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtn17ActionPerformed(evt);
            }
        });

        regbtn6.setText("EMPTY");
        regbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtn6ActionPerformed(evt);
            }
        });

        regbtn10.setText("EMPTY");
        regbtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtn10ActionPerformed(evt);
            }
        });

        regbtn14.setText("EMPTY");
        regbtn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtn14ActionPerformed(evt);
            }
        });

        regbtn18.setText("EMPTY");
        regbtn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtn18ActionPerformed(evt);
            }
        });

        regbtn8.setText("EMPTY");
        regbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtn8ActionPerformed(evt);
            }
        });

        jButton46.setText("Close");
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });

        username.setText("-");

        load.setSelected(true);
        load.setText("Load");
        load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel55)
                    .addComponent(jLabel54)
                    .addComponent(jLabel36)
                    .addComponent(jLabel60))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(load)
                        .addGap(18, 18, 18)
                        .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(regbtn2)
                                    .addGap(18, 18, 18)
                                    .addComponent(regbtn6)
                                    .addGap(18, 18, 18)
                                    .addComponent(regbtn10))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(regbtn1)
                                            .addGap(18, 18, 18)
                                            .addComponent(regbtn5))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(userName)
                                            .addGap(18, 18, 18)
                                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(regDe)
                                            .addGap(46, 46, 46)
                                            .addComponent(regTr)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(regTe)
                                        .addComponent(regbtn9))))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(regbtn14)
                                    .addGap(18, 18, 18)
                                    .addComponent(regbtn18))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(regbtn13)
                                        .addComponent(regPe))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(regPa)
                                        .addComponent(regbtn17)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(regbtn3)
                                    .addGap(18, 18, 18)
                                    .addComponent(regbtn7)
                                    .addGap(18, 18, 18)
                                    .addComponent(regbtn11))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(regbtn4)
                                    .addGap(18, 18, 18)
                                    .addComponent(regbtn8)
                                    .addGap(18, 18, 18)
                                    .addComponent(regbtn12)))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(regbtn15)
                                    .addGap(18, 18, 18)
                                    .addComponent(regbtn19))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(regbtn16)
                                    .addGap(18, 18, 18)
                                    .addComponent(regbtn20))))))
                .addGap(0, 131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userName)
                    .addComponent(username))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regDe)
                    .addComponent(regTr)
                    .addComponent(regPe)
                    .addComponent(regPa)
                    .addComponent(regTe))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regbtn1)
                    .addComponent(regbtn5)
                    .addComponent(regbtn9)
                    .addComponent(regbtn13)
                    .addComponent(regbtn17)
                    .addComponent(jLabel60))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regbtn2)
                    .addComponent(regbtn6)
                    .addComponent(regbtn10)
                    .addComponent(regbtn14)
                    .addComponent(regbtn18)
                    .addComponent(jLabel36))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regbtn3)
                    .addComponent(regbtn7)
                    .addComponent(regbtn11)
                    .addComponent(regbtn15)
                    .addComponent(regbtn19)
                    .addComponent(jLabel54))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regbtn4)
                    .addComponent(regbtn8)
                    .addComponent(regbtn12)
                    .addComponent(regbtn16)
                    .addComponent(regbtn20)
                    .addComponent(jLabel55))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(load)
                    .addComponent(jButton46))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regbtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtn12ActionPerformed
        // TODO add your handling code here:
        idbtn=12;
        cReg.proSetUp(idbtn);
        
          //cReg.getGymnastis();
        //idbtn=12;
        //cReg.proSetUp(1);
       
    }//GEN-LAST:event_regbtn12ActionPerformed

    private void regbtn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtn16ActionPerformed
        // TODO add your handling code here:
        idbtn=16;
        cReg.proSetUp(idbtn);
    }//GEN-LAST:event_regbtn16ActionPerformed

    private void regbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtn2ActionPerformed
        // TODO add your handling code here:
        idbtn=2;
        cReg.proSetUp(idbtn);
    }//GEN-LAST:event_regbtn2ActionPerformed

    private void regbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtn3ActionPerformed
        // TODO add your handling code here:
       idbtn=3;
        cReg.proSetUp(idbtn);
    }//GEN-LAST:event_regbtn3ActionPerformed

    private void regbtn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtn20ActionPerformed
        // TODO add your handling code here:
        idbtn=20;
        cReg.proSetUp(idbtn);
    }//GEN-LAST:event_regbtn20ActionPerformed

    private void regbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtn7ActionPerformed
        // TODO add your handling code here:
        idbtn=7;
        cReg.proSetUp(idbtn);
    }//GEN-LAST:event_regbtn7ActionPerformed

    private void regbtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtn11ActionPerformed
        // TODO add your handling code here:
       idbtn=11;
        cReg.proSetUp(idbtn);
    }//GEN-LAST:event_regbtn11ActionPerformed

    private void regbtn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtn15ActionPerformed
        // TODO add your handling code here:
        idbtn=15;
        cReg.proSetUp(idbtn);
    }//GEN-LAST:event_regbtn15ActionPerformed

    private void regbtn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtn19ActionPerformed
        // TODO add your handling code here:
        idbtn=19;
        cReg.proSetUp(idbtn);
    }//GEN-LAST:event_regbtn19ActionPerformed

    private void regbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtn4ActionPerformed
        // TODO add your handling code here:
        idbtn=4;
        cReg.proSetUp(idbtn);
    }//GEN-LAST:event_regbtn4ActionPerformed

    private void regbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtn1ActionPerformed
        // TODO add your handling code here:
        idbtn=1;
        cReg.proSetUp(idbtn);
       
    }//GEN-LAST:event_regbtn1ActionPerformed

    private void regbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtn5ActionPerformed
        // TODO add your handling code here:
        idbtn=5;
        cReg.proSetUp(idbtn);
       
    }//GEN-LAST:event_regbtn5ActionPerformed

    private void regbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtn9ActionPerformed
        // TODO add your handling code here:
        idbtn=9;
        cReg.proSetUp(idbtn);
       
    }//GEN-LAST:event_regbtn9ActionPerformed

    private void regbtn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtn13ActionPerformed
        // TODO add your handling code here:
       idbtn=13;
        cReg.proSetUp(idbtn);
    }//GEN-LAST:event_regbtn13ActionPerformed

    private void regbtn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtn17ActionPerformed
        // TODO add your handling code here:
       idbtn=17;
        cReg.proSetUp(idbtn);
    }//GEN-LAST:event_regbtn17ActionPerformed

    private void regbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtn6ActionPerformed
        // TODO add your handling code here:
        idbtn=6;
        cReg.proSetUp(idbtn);
    }//GEN-LAST:event_regbtn6ActionPerformed

    private void regbtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtn10ActionPerformed
        // TODO add your handling code here:
        idbtn=10;
        cReg.proSetUp(idbtn);
    }//GEN-LAST:event_regbtn10ActionPerformed

    private void regbtn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtn14ActionPerformed
        // TODO add your handling code here:
        idbtn=14;
        cReg.proSetUp(idbtn);
    }//GEN-LAST:event_regbtn14ActionPerformed

    private void regbtn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtn18ActionPerformed
        // TODO add your handling code here:
        idbtn=18;
        cReg.proSetUp(idbtn);
    }//GEN-LAST:event_regbtn18ActionPerformed

    private void regbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtn8ActionPerformed
        // TODO add your handling code here:
        idbtn=8;
        cReg.proSetUp(idbtn);
    }//GEN-LAST:event_regbtn8ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jButton46ActionPerformed

    private void cancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel2ActionPerformed
        // TODO add your handling code here:
        userdia1.setVisible(false);
    }//GEN-LAST:event_cancel2ActionPerformed

    private void loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadActionPerformed
        // TODO add your handling code here:
        regbtn1.setText(cReg.synedriaList.get(0).getEidiko().getTitlos()+" {"+cReg.synedriaList.get(0).getThesis()+")");
        regbtn2.setText(cReg.synedriaList.get(1).getEidiko().getTitlos()+" {"+cReg.synedriaList.get(1).getThesis()+")");
        regbtn3.setText(cReg.synedriaList.get(2).getEidiko().getTitlos()+" {"+cReg.synedriaList.get(2).getThesis()+")");
        regbtn4.setText(cReg.synedriaList.get(3).getEidiko().getTitlos()+" {"+cReg.synedriaList.get(3).getThesis()+")");
        regbtn5.setText(cReg.synedriaList.get(4).getEidiko().getTitlos()+" {"+cReg.synedriaList.get(4).getThesis()+")");
        regbtn6.setText(cReg.synedriaList.get(5).getEidiko().getTitlos()+" {"+cReg.synedriaList.get(5).getThesis()+")");
        regbtn7.setText(cReg.synedriaList.get(6).getEidiko().getTitlos()+" {"+cReg.synedriaList.get(6).getThesis()+")");
        regbtn8.setText(cReg.synedriaList.get(7).getEidiko().getTitlos()+" {"+cReg.synedriaList.get(7).getThesis()+")");
        regbtn9.setText(cReg.synedriaList.get(8).getEidiko().getTitlos()+" {"+cReg.synedriaList.get(8).getThesis()+")");
        regbtn10.setText(cReg.synedriaList.get(9).getEidiko().getTitlos()+" {"+cReg.synedriaList.get(9).getThesis()+")");
        regbtn11.setText(cReg.synedriaList.get(10).getEidiko().getTitlos()+" {"+cReg.synedriaList.get(10).getThesis()+")");
        regbtn12.setText(cReg.synedriaList.get(11).getEidiko().getTitlos()+" {"+cReg.synedriaList.get(11).getThesis()+")");
        regbtn13.setText(cReg.synedriaList.get(12).getEidiko().getTitlos()+" {"+cReg.synedriaList.get(12).getThesis()+")");
        regbtn14.setText(cReg.synedriaList.get(13).getEidiko().getTitlos()+" {"+cReg.synedriaList.get(13).getThesis()+")");
        regbtn15.setText(cReg.synedriaList.get(14).getEidiko().getTitlos()+" {"+cReg.synedriaList.get(14).getThesis()+")");
        regbtn16.setText(cReg.synedriaList.get(15).getEidiko().getTitlos()+" {"+cReg.synedriaList.get(15).getThesis()+")");
        regbtn17.setText(cReg.synedriaList.get(16).getEidiko().getTitlos()+" {"+cReg.synedriaList.get(16).getThesis()+")");
        regbtn18.setText(cReg.synedriaList.get(17).getEidiko().getTitlos()+" {"+cReg.synedriaList.get(17).getThesis()+")");
        regbtn19.setText(cReg.synedriaList.get(18).getEidiko().getTitlos()+" {"+cReg.synedriaList.get(18).getThesis()+")");
        regbtn20.setText(cReg.synedriaList.get(19).getEidiko().getTitlos()+" {"+cReg.synedriaList.get(19).getThesis()+")");
        //System.out.print("Username:"+cLogin.getUser());
    }//GEN-LAST:event_loadActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        try {
            // TODO add your handling code here:
            cReg.decThesi(idbtn);
           theseis.setText(Integer.toString(cReg.newThesi()));
        } catch (SQLException ex) {
            Logger.getLogger(UIProgramRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_registerActionPerformed
public void SetProg(String hmera,String time,String gymnastis,int aithousa,String prog,int empty) {
        daylb.setText(hmera);
        timelb.setText(time); 
        gymnastislb.setText(gymnastis);
        aithousalb.setText(Integer.toString(aithousa));
        programmalb.setText(prog);
        theseis.setText(Integer.toString(empty));
        userdia1.setVisible(true);
        userdia1.setSize(500,500);
    }
public void SetUser(){
    username.setText(cLogin.getUser());
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIProgramRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIProgramRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIProgramRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIProgramRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIProgramRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aithousalb;
    private javax.swing.JButton cancel2;
    private javax.swing.JLabel daylb;
    private javax.swing.JLabel gymnastislb;
    private javax.swing.JButton jButton46;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JToggleButton load;
    private javax.swing.JLabel programmalb;
    private javax.swing.JLabel regDe;
    private javax.swing.JLabel regPa;
    private javax.swing.JLabel regPe;
    private javax.swing.JLabel regTe;
    private javax.swing.JLabel regTr;
    private javax.swing.JButton regbtn1;
    private javax.swing.JButton regbtn10;
    private javax.swing.JButton regbtn11;
    private javax.swing.JButton regbtn12;
    private javax.swing.JButton regbtn13;
    private javax.swing.JButton regbtn14;
    private javax.swing.JButton regbtn15;
    private javax.swing.JButton regbtn16;
    private javax.swing.JButton regbtn17;
    private javax.swing.JButton regbtn18;
    private javax.swing.JButton regbtn19;
    private javax.swing.JButton regbtn2;
    private javax.swing.JButton regbtn20;
    private javax.swing.JButton regbtn3;
    private javax.swing.JButton regbtn4;
    private javax.swing.JButton regbtn5;
    private javax.swing.JButton regbtn6;
    private javax.swing.JButton regbtn7;
    private javax.swing.JButton regbtn8;
    private javax.swing.JButton regbtn9;
    private javax.swing.JButton register;
    private javax.swing.JLabel theseis;
    private javax.swing.JLabel timelb;
    private javax.swing.JLabel userName;
    private javax.swing.JDialog userdia1;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
